development:
  adapter: postgresql
  encoding: unicode
  database: Receipe_App_development
  pool: 5
  username: postgres
  password: wolo

test:
  adapter: postgresql
  encoding: unicode
  database: Receipe_App_test
  pool: 5
  username: postgres
  password: wolo

production:
  adapter: postgresql
  encoding: unicode
  database: Receipe_App_production
  pool: 5
  username: postgres
  password: wolo
